### ISSUE TITLE
Tracking issue for production readiness

### ISSUE THREAD

**Issue by aneeshusa** [Manishearth/servo-gecko-try#3]
Here's a living checklist of things I'd like to see done before we start running this on our infrastructure.

- [ ] Reduce bus factor:
  - [ ] Potentially move under the `servo` or `servo-automation` org
  - [ ] Set up Homu on this repo
- [ ] Clean up bash style in scripts
- [ ] Run servo-tidy at least once, and ideally add it to CI
- [ ] ~~Set up publishing to PyPi (Salt doesn't work great with pip git dependencies)~~
  - Fixed, see servo/saltfs#593
- [ ] Have a plan for "wipe everything and start from scratch": ideally with a script, but could be just docs
- [ ] Add some operational docs
- [ ] Add some comments, both high-level and e.g. docstrings
- [ ] Add at least a basic test in CI that hits the index endpoint and checks the `Hi` message
